name: app_links
description: Android App Links, Deep Links, iOs Universal Links and Custom URL schemes handler for Flutter (desktop included).
version: 6.2.0
homepage: https://github.com/llfbandit/app_links

environment:
  sdk: ^3.0.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  app_links_platform_interface:
    path: "../app_links_platform_interface"

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.app_links
        pluginClass: AppLinksPlugin
      ios:
        pluginClass: AppLinksPlugin
      linux:
        default_package: app_links_linux
      macos:
        pluginClass: AppLinksMacosPlugin
      web:
        default_package: app_links_web
      windows:
        pluginClass: AppLinksPluginCApi

topics:
  - deeplinks
  - app-links
  - universal-links
  - custom-url-schemes
  - deeplinking
